---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start the docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull amulya365/calcy

    - name: running container
      shell: docker run -it -d amulya365/calcy
